using System.Xml.Linq;
using DiagramForge;

namespace DiagramForge.E2ETests;

/// <summary>
/// End-to-end snapshot tests: diagram source text → full pipeline → SVG → compare to baseline.
/// </summary>
/// <remarks>
/// <para>
/// Each <c>Fixtures/*.input</c> file is rendered through <see cref="DiagramRenderer"/> and compared
/// to the matching <c>*.expected.svg</c> baseline. Comparison is XML-canonical (parsed via
/// <see cref="XDocument"/>) so differences in whitespace or attribute serialization order do not
/// cause spurious failures — only structural or value changes trip the assert.
/// </para>
/// <para>
/// <b>Baselines</b> are regenerated by running with <c>UPDATE_SNAPSHOTS=1</c>. This writes the
/// new <c>.expected.svg</c> files back into the <em>source</em> fixture directory (not <c>bin/</c>)
/// so the diff is visible in source control. Review the diff before committing — a layout or
/// render regression will look like a "baseline update". A guard fails fast if this env var
/// is set in CI to prevent accidental auto-accept on the build agent.
/// </para>
/// <para>
/// <b>Adding a fixture:</b> drop a <c>.input</c> file in <c>Fixtures/</c>, run with
/// <c>UPDATE_SNAPSHOTS=1</c>, eyeball the generated <c>.expected.svg</c>, commit both.
/// </para>
/// <para>
/// <b>Artifacts:</b> every run writes the rendered SVG for each fixture to
/// <c>{repo}/artifacts/test-results/snapshots/{fixture}.actual.svg</c> (gitignored).
/// On failure, open that file and the committed <c>.expected.svg</c> side-by-side in a browser.
/// In CI, upload the <c>artifacts/</c> directory as a build artifact to get a downloadable
/// gallery of exactly what the PR renders.
/// </para>
/// </remarks>
public class SnapshotTests
{
    private static readonly DiagramRenderer Renderer = new();

    // Fixture directory as copied to the build output.
    private static readonly string RuntimeFixturesDir =
        Path.Combine(AppContext.BaseDirectory, "Fixtures");

    // Fixture directory in the source tree. Resolved by walking up from the
    // build output until a Fixtures/ sibling is found — robust to Debug/Release
    // and custom output paths.
    private static readonly Lazy<string> SourceFixturesDir = new(LocateSourceFixturesDirectory);

    // Repo root (first ancestor containing a .slnx or .git) — artifacts are anchored here
    // so CI can upload a single predictable path no matter where `dotnet test` runs from.
    private static readonly Lazy<string> RepoRoot = new(LocateRepoRoot);

    // Where rendered output lands on every run (gitignored). Lazy-created first time a
    // test writes to it; the Lazy<T> wrapper makes directory creation single-shot and
    // thread-safe under xUnit's parallel execution.
    private static readonly Lazy<string> ArtifactsDir = new(() =>
    {
        var path = Path.Combine(RepoRoot.Value, "artifacts", "test-results", "snapshots");
        Directory.CreateDirectory(path);
        return path;
    });

    private static bool UpdateSnapshots =>
        Environment.GetEnvironmentVariable("UPDATE_SNAPSHOTS") is "1" or "true";

    private static bool IsCi =>
        Environment.GetEnvironmentVariable("CI") is "1" or "true"
        || Environment.GetEnvironmentVariable("TF_BUILD") is not null
        || Environment.GetEnvironmentVariable("GITHUB_ACTIONS") is "true";

    // ── Test data ─────────────────────────────────────────────────────────────

    public static TheoryData<string> Fixtures
    {
        get
        {
            var data = new TheoryData<string>();
            if (!Directory.Exists(RuntimeFixturesDir))
                return data; // empty — the safety-net test below will flag this

            foreach (var input in Directory.EnumerateFiles(RuntimeFixturesDir, "*.input").OrderBy(f => f))
            {
                data.Add(Path.GetFileNameWithoutExtension(input));
            }
            return data;
        }
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    [Theory]
    [MemberData(nameof(Fixtures))]
    public async Task RenderedOutput_MatchesSnapshot(string fixtureName)
    {
        Assert.False(UpdateSnapshots && IsCi,
            "UPDATE_SNAPSHOTS is set in a CI environment. Refusing to auto-accept baselines on the build agent.");

        var inputPath = Path.Combine(RuntimeFixturesDir, fixtureName + ".input");
        var expectedPath = Path.Combine(RuntimeFixturesDir, fixtureName + ".expected.svg");

        var source = await File.ReadAllTextAsync(inputPath, TestContext.Current.CancellationToken);
        var actualSvg = Renderer.Render(source);

        // Persist the rendered output unconditionally — *before* any assertions — so it
        // survives test failure and lands in the CI artifact upload either way.
        var artifactPath = Path.Combine(ArtifactsDir.Value, fixtureName + ".actual.svg");
        await File.WriteAllTextAsync(artifactPath, actualSvg, TestContext.Current.CancellationToken);

        if (UpdateSnapshots)
        {
            var target = Path.Combine(SourceFixturesDir.Value, fixtureName + ".expected.svg");
            await File.WriteAllTextAsync(target, actualSvg, TestContext.Current.CancellationToken);
            // Also refresh the bin/ copy so a subsequent non-update run in the same build output
            // does not see a stale baseline.
            await File.WriteAllTextAsync(expectedPath, actualSvg, TestContext.Current.CancellationToken);
            return;
        }

        Assert.True(File.Exists(expectedPath),
            $"Missing baseline: {fixtureName}.expected.svg. " +
            $"Run once with UPDATE_SNAPSHOTS=1 to generate it, review, then commit.");

        var expectedSvg = await File.ReadAllTextAsync(expectedPath, TestContext.Current.CancellationToken);
        AssertXmlEqual(expectedSvg, actualSvg, fixtureName, artifactPath);
    }

    /// <summary>
    /// Safety net: fail loudly if discovery found zero fixtures (e.g., the copy-to-output
    /// glob broke or the directory is misnamed). Without this, a broken pipeline would
    /// silently "pass" with no tests executed.
    /// </summary>
    [Fact]
    public void Fixtures_DirectoryIsNotEmpty()
    {
        Assert.True(Directory.Exists(RuntimeFixturesDir),
            $"Fixture directory not found at {RuntimeFixturesDir}. " +
            $"Check the <None Include=\"Fixtures\\**\\*.input\"/> item group in the .csproj.");

        var count = Directory.EnumerateFiles(RuntimeFixturesDir, "*.input").Count();
        Assert.True(count > 0, "No .input fixtures found — snapshot tests are not exercising anything.");
    }

    // ── XML-canonical comparison ──────────────────────────────────────────────

    private static void AssertXmlEqual(string expected, string actual, string fixtureName, string artifactPath)
    {
        // XDocument.Parse normalizes insignificant whitespace; ToString(SaveOptions.None)
        // re-serializes attributes in declaration order (which for a single-writer renderer
        // is deterministic). Net effect: we compare structure + values, not bytes.
        string Canon(string xml) => XDocument.Parse(xml).ToString(SaveOptions.None);

        var canonExpected = Canon(expected);
        var canonActual = Canon(actual);

        if (canonExpected == canonActual)
            return;

        // Hand-roll a minimal line diff for the failure message — far more actionable
        // than Assert.Equal's truncated dump on a multi-KB SVG.
        var expLines = canonExpected.Split('\n');
        var actLines = canonActual.Split('\n');
        int max = Math.Max(expLines.Length, actLines.Length);
        int firstDiff = Enumerable.Range(0, max)
            .FirstOrDefault(i =>
                i >= expLines.Length ||
                i >= actLines.Length ||
                expLines[i] != actLines[i],
                defaultValue: -1);

        string At(string[] a, int i) => i < a.Length ? a[i] : "<end-of-document>";

        // Report paths relative to the repo root so they're usable in CI logs
        // (where absolute agent paths are noise) and clickable locally.
        var expectedRel = Path.Combine("tests", "DiagramForge.E2ETests", "Fixtures", fixtureName + ".expected.svg");
        var actualRel = Path.GetRelativePath(RepoRoot.Value, artifactPath);

        Assert.Fail(
            $"Snapshot mismatch: {fixtureName}\n" +
            $"  expected: {expectedRel}\n" +
            $"  actual:   {actualRel}\n" +
            $"First difference at canonical line {firstDiff + 1}:\n" +
            $"  - {At(expLines, firstDiff)}\n" +
            $"  + {At(actLines, firstDiff)}\n" +
            $"Open both SVG files in a browser to spot the visual difference. " +
            $"If the change is intentional, run with UPDATE_SNAPSHOTS=1 and review the git diff.");
    }

    // ── Source-tree fixture locator ───────────────────────────────────────────

    private static string LocateSourceFixturesDirectory()
    {
        // Walk up from bin/Debug/net10.0/ until we find a Fixtures/ directory
        // that is NOT the build-output copy. Identify it by the presence of a
        // sibling .csproj (the source tree has one; bin/ does not).
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName, "Fixtures");
            if (Directory.Exists(candidate) && dir.EnumerateFiles("*.csproj").Any())
                return candidate;
            dir = dir.Parent;
        }
        throw new DirectoryNotFoundException(
            "Could not locate the source-tree Fixtures/ directory by walking up from " +
            AppContext.BaseDirectory);
    }

    private static string LocateRepoRoot()
    {
        // Anchor on the solution file or .git — whichever appears first walking up.
        // .slnx is preferred (works in worktrees / source archives without .git).
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (dir.EnumerateFiles("*.slnx").Any() || Directory.Exists(Path.Combine(dir.FullName, ".git")))
                return dir.FullName;
            dir = dir.Parent;
        }
        throw new DirectoryNotFoundException(
            "Could not locate the repo root (no .slnx or .git found) walking up from " +
            AppContext.BaseDirectory);
    }
}
