namespace DiagramForge.Models;

/// <summary>
/// Shared helpers for deriving diagram color palettes from a <see cref="Theme"/>.
/// Diagram-specific layout code delegates color policy here so the underlying
/// hue rotation, hue-distance scoring, and palette derivation logic can be
/// reused across diagram kinds.
/// </summary>
public static class ThemePaletteResolver
{
    /// <summary>
    /// Builds an array of <paramref name="ringCount"/> visually distinct ring colors
    /// derived from the theme palette.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The first entry is always <paramref name="outerColor"/>. Subsequent entries are
    /// chosen from a candidate pool built from theme semantic colors and
    /// <see cref="Theme.NodePalette"/> entries, maximizing hue distance from colors
    /// already selected and from <paramref name="centerColor"/>.
    /// </para>
    /// <para>
    /// When the candidate pool is exhausted, fallback colors are generated by
    /// rotating the last chosen color's hue by 55°.
    /// </para>
    /// </remarks>
    /// <param name="theme">Theme supplying semantic colors and optional palette.</param>
    /// <param name="ringCount">Number of ring colors to produce.</param>
    /// <param name="centerColor">Center node fill color — used for hue-distance contrast.</param>
    /// <param name="outerColor">Color for the outermost ring (index 0).</param>
    /// <param name="isLightBackground">
    /// Controls lightness clamping when generating fallback colors via hue rotation.
    /// </param>
    public static string[] BuildRingColors(Theme theme, int ringCount, string centerColor, string outerColor, bool isLightBackground)
    {
        ArgumentNullException.ThrowIfNull(theme);
        if (ringCount < 1)
            throw new ArgumentOutOfRangeException(nameof(ringCount), ringCount, "ringCount must be at least 1.");

        var colors = new List<string>(ringCount)
        {
            outerColor,
        };

        if (ringCount == 1)
            return [.. colors];

        var candidatePool = new List<string>
        {
            ColorUtils.Vibrant(theme.SecondaryColor, 2.4),
            ColorUtils.Vibrant(theme.AccentColor, 2.4),
            ColorUtils.Vibrant(ColorUtils.Blend(theme.SecondaryColor, theme.AccentColor, 0.5), 2.6),
            ColorUtils.Vibrant(ColorUtils.Blend(theme.AccentColor, theme.PrimaryColor, 0.35), 2.5),
            ColorUtils.Vibrant(ColorUtils.Blend(theme.PrimaryColor, theme.SecondaryColor, 0.25), 2.5),
            ColorUtils.RotateHue(theme.SecondaryColor, 34, isLightBackground),
            ColorUtils.RotateHue(theme.AccentColor, -34, isLightBackground),
            ColorUtils.RotateHue(theme.PrimaryColor, 52, isLightBackground),
        };

        if (theme.NodePalette is { Count: > 0 })
        {
            foreach (var paletteColor in theme.NodePalette)
            {
                candidatePool.Add(ColorUtils.Vibrant(paletteColor, 2.6));
                candidatePool.Add(ColorUtils.RotateHue(paletteColor, 28, isLightBackground));
            }
        }

        var distinctCandidates = candidatePool
            .Select(color => ColorUtils.Blend(color, theme.BackgroundColor, isLightBackground ? 0.06 : 0.10))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Where(color => ColorUtils.GetHueDistance(color, outerColor) >= 18)
            .ToList();

        while (colors.Count < ringCount)
        {
            string? nextColor = distinctCandidates
                .OrderByDescending(candidate => ColorUtils.GetMinimumHueDistance(candidate, colors.Append(centerColor)))
                .ThenByDescending(candidate => ColorUtils.GetContrastRatio(candidate, theme.BackgroundColor))
                .FirstOrDefault();

            if (nextColor is null)
            {
                nextColor = ColorUtils.RotateHue(colors[^1], 55, isLightBackground);
            }
            else
            {
                distinctCandidates.Remove(nextColor);
            }

            colors.Add(nextColor);
        }

        return [.. colors];
    }
}
